### ISSUE TITLE
Configuration issues with the latest version (1.3 v2.2022.1)

### ISSUE THREAD

**Issue by mrflamist** [Novetus/Novetus_src#40] opened 2022-03-06 11:46 UTC
## **Summary:**
Novetus client launcher refuses to read information from the config file (at least not correctly) but is capable of writing. Everything other than graphics options gets reset. The theme selection doesn't work and shows up as a blank field on start. The launcher claims it is version 1.0, despite the correct version number being up in the title. Please see the screenshots and the error log pasted below for more info.
Other than that, the launcher functions as intended (or at least as good as my friend's launcher).

## **System info:**
**OS:** Windows 7 Professional x64
**Redistributables:**
- Microsoft .NET Framework 4.7.1
-  Visual C++ 2005 x86 (8.0.61001 and 8.0.59193)
-  Visual C++ 2005 x64 (8.0.56336 and 8.0.61000)

## **Steps taken to try and resolve this:**
-moving the files to the desktop
-moving them to the "C:\Novetus\" directory
-opening the launcher from "Novetus_launcher_legacy.bat"
-opening the launcher from "NovetusBootstrapper.exe"
-setting the "Novetus.exe" to start as an administartor
-enabling Windows Features like Media Player, Internet Explorer 8, etc.

## **Screenshots:**
**All input fields return to default after reopening:**
![image](https://user-images.githubusercontent.com/88791223/156920107-dcb4b162-6750-4525-8510-f9959b18e484.png)

**Options menu as it appears when opening Novetus:**
![image](https://user-images.githubusercontent.com/88791223/156920028-ee785b4f-fb49-4e32-8fc7-94244e74f4ab.png)

**Trying to change themes:**
![image](https://user-images.githubusercontent.com/88791223/156920053-5f0504e5-e110-4ebd-bd48-1bb52502f9eb.png)

**However, it appears the Novetus launcher sees the config file as it can save the settings:**
![image](https://user-images.githubusercontent.com/88791223/156920210-89b67f2e-d02b-4527-8d4a-aa2f71f99b81.png)

**Changing the "style" variable from "3" to "2" or "1" does seem to do something:**
![image](https://user-images.githubusercontent.com/88791223/156920321-321f2c8f-05fc-4ad7-a62f-91cf8ef2cc1c.png)

**Here are the contents of that error message:**

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Convert.ToDouble(String value)
   at Splash.DecodeSplashString(String text)
   at Splash..ctor(String text, Boolean specialSplashMode)
   at SplashReader.GetSpecialSplash()
   at SplashReader.GetSpecialOrNormalSplash()
   at SplashReader.GetSplash()
   at NovetusLauncher.LauncherFormShared.InitForm()
   at NovetusLauncher.LauncherFormExtended.MainFormLoad(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Novetus
    Assembly Version: 1.3.8067.13871
    Win32 Version: 1.3.8067.13871
    CodeBase: file:///C:/Users/Exiled%20Freak/Desktop/Novetus/bin/Novetus.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
NLog
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2.11786
    CodeBase: file:///C:/Users/Exiled%20Freak/Desktop/Novetus/bin/NLog.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**After clicking "continue":**
![image](https://user-images.githubusercontent.com/88791223/156920475-1c1fb048-1ad5-406c-9cbf-39e8eccaf9f3.png)

**Comment by Bitl** [comment] 2022-03-06 14:45
this is caused by not extracting Novetus all the way or running Novetus from the 7z file. You NEED to extract the entirety of Novetus before running it. This is part of why the readme isn't showing up in the options and there's an error caused by special splashes.

**Comment by Bitl** [comment] 2022-03-06 17:33
This seems to be a deeper issue than just unextracted files, will investigate

**Comment by torskyy** [comment] 2022-03-19 13:39
Having the same issue here, the only difference is im on Windows 10.

**Comment by Bitl** [comment] 2022-04-13 19:30
fixed as of the latest snapshot

**Closed** 2022-04-13 19:29 UTC
